# https://www.appveyor.com/docs/appveyor-yml/
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
# version: 1.0.{build}

# os to use
image:
  - Visual Studio 2022
  - Ubuntu

# branches to build
branches:
  # whitelist
  only:
    - master
    - /v\d+\.\d+\.\d+/

# set clone depth
clone_depth: 1

build_script:
  - dotnet --info
  - dotnet build -c Release

after_build:
  - sh: dotnet publish QarnotCLI/QarnotCLI.csproj -c Release -r osx-x64 --self-contained true /p:PublishSingleFile=true -o ./artifacts/osx
  - sh: mv ./artifacts/osx/qarnot ./artifacts/qarnot-osx-x64
  - sh: dotnet publish QarnotCLI/QarnotCLI.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true -o ./artifacts/linux
  - sh: mv ./artifacts/linux/qarnot ./artifacts/qarnot-linux-x64
  - sh: dotnet publish QarnotCLI/QarnotCLI.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ./artifacts/windows
  - sh: mv ./artifacts/windows/qarnot.exe ./artifacts/qarnot-windows-x64.exe
  - sh: rm -f artifacts/*/*.pdb
  - sh: rm -f artifacts/windows/qarnot.xml  # only keep one version of this, otherwise it'll fail to upload to Github (duplicate)
  - sh: rm -f artifacts/osx/qarnot.xml  # only keep one version of this, otherwise it'll fail to upload to Github (duplicate)

test_script:
  - sh: dotnet test ./*.Test   # Will run in Ubuntu image
  - cmd: dotnet test           # Will run in Windows image

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

artifacts:
  - path: artifacts/**/*
    name: qarnot
  - path: artifacts/
    name: binaries-zip
    type: zip

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: qarnot,binaries-zip
    description: "Cli to use Qarnot's computing service"
    draft: false
    prerelease: false
    auth_token:
      secure: BjDHLTlj5/37u7j3aMubt/8BMCgS4vzY3w82StMf7edYYerpVdcs1uIdL79wbCF5
    on:
      APPVEYOR_REPO_TAG: true
