# https://www.appveyor.com/docs/appveyor-yml/
# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
# version: 1.0.{build}

# os to use
image:
  - Visual Studio 2019
  - Ubuntu

# branches to build
branches:
  # whitelist
  only:
    - master

# set clone depth
clone_depth: 1

build_script:
  - dotnet --info
  - dotnet build -c Release

after_build:
  - sh: dotnet publish qarnot -c Release -r ubuntu-x64 /p:PublishSingleFile=true -o ./artifacts
  - cmd: dotnet publish qarnot -c Release -r win10-x64 /p:PublishSingleFile=true -o ./artifacts
  - ls artifacts
  - rm artifacts/*.pdb

test_script:
  - sh: dotnet test ./*.Test
  - cmd: dotnet test

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

artifacts:
  - path: artifacts\*
    name: qarnot

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: qarnot
    description: "Cli to use Qarnot's computing service"
    draft: false
    prerelease: true
    auth_token: $(github_token)
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
